### ISSUE TITLE
_

### ISSUE THREAD

**Issue by ghost** [moq/labs#7]
_

**Comment by kzu** [comment]
If this is about moq v4, please report at https://github.com/moq/moq4/issues

Thanks!

**Comment by megamindbrian** [comment]
@kzu Can you move it administratively and actually be helpful instead of just closing issues without thought?

**Comment by stakx** [comment]
@megamindbrian - I saw your issue when you opened it, but chose not to answer because I perceived it to be more of a general complaint / rant than an actual specific problem statement.

> Any insight in to some good patterns that solve this problem?

What problem, specifically? That you cannot mock classes with Moq? But you can! There are just certain well-known limitations (which are not unique to Moq).

> * I also shouldn't have to expose everything as virtual, just to write a unit a test.
> * I also shouldn't have to make an interface that is never overridden, just to write unit tests.

May I suggest to you an experiment? Take some code you want to test, and write your mocks manually; that is, without any helper library such as Moq. Try to find a way to mock a sealed class, and/or one where none of the methods are virtual, and/or one that doesn't implement any interfaces. Then see how well that goes. You just *might* discover the reasons why Moq's support for mocking classes is limited the way it is.

Moq does not have any magic powers. It just automates at run-time what you'd otherwise have to do manually, but it is subject to the same limitations you'd also run into, if you did all the work yourself.

> * I shouldn't have to purchase from a third party in order to write nice code with C#.

Please remember that you are filing this issue with an open-source project. We're trying to make Moq a great library, and we're making that effort in our free time. We don't get paid for it, and neither are we asking you for your money.

You don't need to pay anyone any money to "write nice code with C#". Noone is going to stop you from writing your own mocking library, if you're unhappy with Moq (or any other comparable library, for that matter).

If you want to mock sealed classes, or classes with non-virtual methods, or even static methods, I suggest you look into the .NET Framework's Profiling API. That's the one on which tools such as TypeMock Isolator or Microsoft Fakes (or whatever it's called these days) are based on. It's the *only* way to mock static, sealed methods. Be also aware that it's only available on the full .NET Framework, so by using it, you sacrifice cross-platform compatibility (which is one reason why Moq doesn't use it).

**Comment by kzu** [comment]
couldn't have written it better than @stakx. Also, @megamindbrian if wouldn't hurt to understand how mocking libraries do what they do. I can suggest http://blogs.clariusconsulting.net/kzu/mocks-stubs-and-fakes-its-a-continuum/ which should give you either a (manual) alternative or a deeper understanding of how and why Moq was created and what problem it solves with the capabilities .NET gives us.
